export const COLOR_WHITE = '#ffffff'
export const COLOR_GREEN = '#52c41a'
export const COLOR_LIGHT_GREEN = '#f6ffed'
export const COLOR_GRAY = '#d9d9d9'
export const COLOR_BLUE = '#1890ff'
export const COLOR_LIGHT_BLUE = '#e6f7ff'
export const COLOR_BLACK = '#000000d9'
